# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.19.5
loom_version=1.8.13

# Mod Properties
mod_version=1.0.0
maven_group=dev.wexra
archives_base_name=wexraclient

# Dependencies
fabric_version=0.115.1+1.21.4
